" -- install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" -- complete brackets, parentheses, ...
Plug 'jiangmiao/auto-pairs'

" -- dev icons
Plug 'ryanoasis/vim-devicons'

" -- markdown
Plug 'shime/vim-livedown'

" Initialize plugin system
call plug#end()

" ************* editor configuration *************
filetype plugin on
filetype indent on
syntax on
set tabstop=4
set shiftwidth=4
set nohlsearch
set autoread
set t_Co=256
set scrolloff=8
set encoding=UTF-8
set lazyredraw
set showmatch
let python_highlight_all = 1

" ************* eye-candy configuration *************
" show line numbers
set nu
