#
# User configuration sourced by interactive shells
#

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

# Path
export PATH=~/.local/bin:$PATH

# Custom aliases
alias lc=colorls
alias grep='grep --color=auto'
alias pmount='mount -o gid=users,fmask=113,dmask=002'
alias pbcopy='xsel --clipboard --input'

# Cursor speed
# xset r rate 200 20
