#
# User configuration sourced by interactive shells
#

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

# Exports
export PATH=~/.local/bin:$PATH
export VISUAL=vim

# Custom aliases
alias lc=colorls
alias grep='grep --color=auto'
alias pmount='mount -o gid=users,fmask=113,dmask=002'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'

# Helper aliases
alias heredoc='echo -e "cat << EOF > /tmp/file\nThese contents will be written to the file.\nEOF"'

# Cursor speed
# xset r rate 200 20

# Conda
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh
