window:
    dimensions:
        columns: 70
        lines: 18

    padding:
        x: 20
        y: 20

    dynamic_padding: true
    decorations: full

scrolling:
    history: 2000


tabspaces: 4

font:
    # The normal (roman) font face to use.
    # Style can be specified to pick a specific face.
    normal:
        family: "Iosevka Term"
        style: Regular

    # The bold font face
    bold:
        family: "Iosevka Term"
        style: Bold

    # The italic font face
    italic:
        family: "Source Code Pro"
        style: "Medium Italic"

    # Point size of the font
    size: 15.0

# Colors (Dracula)
colors:
    # Default colors
    primary:
        background: '0x161925'
        foreground: '0xf8f8f2'

    # Normal colors
    normal:
        black:   '0x000000'
        red:     '0xff5555'
        green:   '0x50fa7b'
        yellow:  '0xf1fa8c'
        blue:    '0xcaa9fa'
        magenta: '0xff79c6'
        cyan:    '0x8be9fd'
        white:   '0xbfbfbf'

    # Bright colors
    bright:
        black:   '0x575b70'
        red:     '0xff6e67'
        green:   '0x5af78e'
        yellow:  '0xf4f99d'
        blue:    '0xcaa9fa'
        magenta: '0xff92d0'
        cyan:    '0x9aedfe'
        white:   '0xe6e6e6'
